FROM pyotr777/celery-chainer:latest
# Install Flower

MAINTAINER Bryzgalov Peter <peterbryz@yahoo.com>

RUN pip install flower
RUN pip install -U pyyaml

CMD ["celery","flower"]

# docker build -f ML/mlframework/Dockerfile-flower -t pyotr777/celery-chainer-flower