FROM pyotr777/celery-chainer-flower

MAINTAINER Bryzgalov Peter <peterbryz@yahoo.com>

# Install Jupyter

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    checkinstall bzip2 ca-certificates sudo locales \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y gfortran && apt-get -y autoremove

RUN apt-get install -y libtiff5-dev libjpeg-dev && apt-get -y autoremove

RUN apt-get install -y python-numpy python-scipy python-pandas \
    python-tk && apt-get -y autoremove

RUN /usr/bin/python --version

RUN pip install -U pip
RUN pip install -U nose
RUN pip install -U jupyter
RUN pip install -U matplotlib
RUN pip install -U Pillow
RUN pip install -U sklearn
RUN pip install -U h5py
RUN pip install -U pyyaml

WORKDIR /root/
CMD jupyter notebook --no-browser --ip=0.0.0.0 --NotebookApp.token=""

# docker build -f ML/mlframework/Dockerfile-jupyter -t pyotr777/celery-chainer-jupyter