FROM pyotr777/celery-chainer:latest

# Celery worker container

MAINTAINER Bryzgalov Peter <peterbryz@yahoo.com>

RUN groupadd user && useradd -m --home-dir /home/user -g user user

ENV CELERY_BROKER_URL amqp://guest@rabbit

USER user
CMD ["celery", "worker"]

# docker build -f ML/mlframework/Dockerfile-worker -t pyotr777/celery-chainer-worker